import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SmoothScrollProvider } from "@/components/providers/SmoothScrollProvider";
import BackgroundCanvas from "@/components/shader-background/BackgroundCanvas";
import { BubblesCanvas } from "@/components/bubbles/bubblesCanvas";
import ViewCanvas from "@/components/ViewCanvas";
import Header from "@/components/layout/Header";
import Social from "@/components/social/Social";
import Footer from "@/components/layout/Footer";

const creamCake = localFont({
  variable: "--font-cream-cake",
  src: "../public/font/Cream Cake.otf",
});

const poppins = localFont({
  variable: "--font-poppins",
  src: "../public/font/poppins-extrabold.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${poppins.variable} ${creamCake.variable} scrollbar scrollbar-none overflow-x-hidden antialiased`}
      >
        {/* Global Background */}
        <BackgroundCanvas />
        <BubblesCanvas />
        <ViewCanvas />
        <Header />
        <SmoothScrollProvider>
          <main className="bg-primary">{children}</main>
        </SmoothScrollProvider>
        <Social />
        <Footer />
      </body>
    </html>
  );
}
